### ISSUE TITLE
You should say how it works in the README

### ISSUE THREAD

**Issue by paul-hammant** [sdwolfe32/trumail#1]
"This marks an email as valid if it has an @ character in it"

"This checks DNS MX records for the domain"

"This sends a test email and if there is no bounce it marks the email as verified"

"This requires the email owner to RSVP"

"This uses a DAT file purloined from the dark net containing all pwned emails"

"This leverages quantum computing resources in a parallel universe and just effing knows 1ms before being asked whether an email address exists or not"

**Comment by sdwolfe32** [comment]
Ahh, Good idea! Will do.

**Comment by paul-hammant** [comment]
:)
