### ISSUE TITLE
Result detail

### ISSUE THREAD

**Issue by ganeshthandapani** [sdwolfe32/trumail#10]
Hi,
Realy nice work from you. Thanks a lot. One more thing while checking the email, output is ok if you also add the result detail it will be to more better. For example, if  I verify this email( s.m.bester@earthlink.net) my deliverable status is false. Its fine but why this email gets failed, for that, if you display a Result Detail message it really helps to understand.

**Comment by sdwolfe32** [comment]
I don’t know why I didn’t think of this... I love this idea and I’ll work on adding more details in the response!

**Comment by sdwolfe32** [comment]
I've added more detailed error responses to the output. Sorry if the errors were to vague before. I'd like to also output a debug trace as well but that's an unplanned feature right now.
