### ISSUE TITLE
Whats about proxy?

### ISSUE THREAD

**Issue by monobook** [sdwolfe32/trumail#15]
Hi

What do you think about proxy support? Maybe TOR?

**Comment by sdwolfe32** [comment]
That's beyond the scope of this project. As of right now there are no plans of piping any of my requests through a proxy

**Comment by zxfrank** [comment]
I had the same issue, created a pull request #29

**Comment by sdwolfe32** [comment]
This is not an issue. As I stated it is not in the scope of this project right now. If you'd like this feature you can check out zxfranks fork - https://github.com/technosolutionscl/trumail
