### ISSUE TITLE
Self-Hosted in Windows does not pass

### ISSUE THREAD

**Issue by shawkaty** [sdwolfe32/trumail#20]
Great work. When I run the main.go in Windows 10 environment, I received the following errors:

# golang.org/x/net/context
trml\src\golang.org\x\net\context\context.go:45:19: undefined: Context
trml\src\golang.org\x\net\context\context.go:46:9: undefined: background
trml\src\golang.org\x\net\context\context.go:54:13: undefined: Context
trml\src\golang.org\x\net\context\context.go:55:9: undefined: todo
# golang.org/x/net/idna
trml\src\golang.org\x\net\idna\punycode.go:31:42: undefined: labelError

**Comment by sdwolfe32** [comment]
Something is wrong with your dependency versioning. Please use glide to install your dependencies and try again.
