### ISSUE TITLE
getJSON Method - Unexpected token :

### ISSUE THREAD

**Issue by kellerisddev** [sdwolfe32/trumail#24]
Using AJAX getJSON method to validate email addresses and I am receiving the following syntax error

`jQuery.ajax({url: "https://trumail.io/json/"+addr, dataType: 'jsonp', success: function(result){
        console.log("Stuff is here: "+result);
    }});`

Uncaught SyntaxError: Unexpected token :

**Comment by sdwolfe32** [comment]
I'm not familiar with javascript or ajax requests but I have not yet implemented jsonp support since I'm not having an easy time wrapping my head around it. If you'd like to contribute and add JSONP support yourself that could potentially fix your issue.

**Comment by sdwolfe32** [comment]
JSONP is now supported. Be sure to call the endpoint using the following URI scheme:

`https://trumail.io/jsonp/{email}?callback={your_callback_name}`
