### ISSUE TITLE
Simple run

### ISSUE THREAD

**Issue by misiekkiller** [sdwolfe32/trumail#25]
{"time":"2018-04-10T01:19:50.92199198Z","level":"ERROR","prefix":"echo","file":"echo.go","line":"340","message":"code=404, message=Not Found"}

I have this error when i try to run trumail source code(without any changes except source address in config) on inteligo but i dont have any problems  when i use docker, any ideas where is the problem ?

**Comment by sdwolfe32** [comment]
You probably did go get to install your dependencies.. The latest labstack/echo broke the app so I had to use an older version. Please use `make glide` to install the dependencies
