### ISSUE TITLE
PROXY request

### ISSUE THREAD

**Issue by misiekkiller** [sdwolfe32/trumail#28]
Is there any way to send trumail local server requests through PROXY?

**Comment by zxfrank** [comment]
you mean inbound or outbound?

**Comment by zxfrank** [comment]
If you want to use an outbound proxy, you can edit main.go and add
`
transport := http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, Proxy: http.ProxyFromEnvironment}
client := &http.Client{Transport: &transport}
`
and replace
`resp, err := http.Get("https://api.ipify.org/")`
with
`resp, err := client.Get("https://api.ipify.org/")`

do the same with httpclient/client.go on line 27
`Client:  &http.Client{Timeout: timeout, Transport: &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, Proxy: http.ProxyFromEnvironment}},`


![image](https://user-images.githubusercontent.com/1887075/38889360-87a6ad6a-424c-11e8-9709-5a663481a6fb.png)

**Comment by sdwolfe32** [comment]
This only proxies requests made to ipify. As far as I can see this shouldn't change any of the communication to the mail servers.

However, to answer your question misiekkiller, (as stated https://github.com/sdwolfe32/trumail/issues/15) proxying traffic between Trumail and the mail servers is currently out of the scope of this project. I have no intentions right now of implementing this. Maybe sometime in the future when the project is a little more stable/complete.
