### ISSUE TITLE
Steps to build custom docker image

### ISSUE THREAD

**Issue by zxfrank** [sdwolfe32/trumail#30]
Hello, I'm trying to `docker build .`
I did make glide
maybe I'm missing something

> Sending
> build context to Docker daemon  51.79MB
> Step 1/6 : FROM alpine:latest
>  ---> 3fd9065eaf02
> Step 2/6 : RUN apk add --no-cache ca-certificates
> ---> Using cache
> ---> c2853ab3189f
>Step 3/6 : ADD trumail /usr/local/bin/trumail
>ADD failed: stat /var/lib/docker/tmp/docker-builder162298542/trumail: no such file or directory

Docker version 18.03.0-ce, build 0520e24

**Comment by sdwolfe32** [comment]
You need to build the trumail binary before calling `docker build .`. The steps are outlined in https://github.com/sdwolfe32/trumail/blob/master/.circleci/config.yml but the exact commands you should run are 
```
go get github.com/Masterminds/glide
make glide
env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
docker build .
```
You should then be able to docker run it

**Comment by zxfrank** [comment]
Ok thanks
