### ISSUE TITLE
Batch Verification

### ISSUE THREAD

**Issue by cindersec** [sdwolfe32/trumail#32]
Eh. You have no database. WTF?!?! Raw heroku 

use golang + whatever mysql , nosql

or maybe try if you see a future . Postgres10 + ElasticSearch  :) 
This way already verified stuff you have stored already.

but what do I know. My github is empty :(

**Comment by sdwolfe32** [comment]
There's no database because I don't want to store anything. The purpose of the project being open source is to prove as best I can that I don't store sensitive data. I would also prefer not to serve stale data to users and perform fresh verifications on request.
