### ISSUE TITLE
add rethinkDB

### ISSUE THREAD

**Issue by cindersec** [sdwolfe32/trumail#37]
Add rethinkDB driver with Golang. 

https://github.com/vodolaz095 Is my dev.

Reason rethinkDB and and storing a database is because it makes it easier to verify a email once you know it’s verified.

**Comment by sdwolfe32** [comment]
I already said I don't want to store secure data. If I do decide to cache lookups in a database they will be encrypted and likely go into MySQL since I already have a solid production mysql db.

**Comment by cindersec** [comment]
Yes please MySQL is fine cuts time off since I did this. Also what type of encryption. Imo MD5 is what I did

**Comment by cindersec** [comment]
Postgres aswell

**Comment by cindersec** [comment]
Postgres10 with new json + elasticsearch mann oh man

**Comment by sdwolfe32** [comment]
Yeah I'm going to key the lookups with MD5... and avoid writing actual emails to the db - just store the actual verification data

**Comment by cindersec** [comment]
2.4 'Verify Task': Verify E-Mail Lists. Allow to verify domains in input lists of emails or domain list files. MaxRetries: 3, MaxTimeout:30seg. Max Execution Threads: 100. Edit /etc/resolv.conf to add new IPs to DNS list. The Syntaxes is following (the angles are referencials, do not put them): {<3>;;;;} extract all domains from these lists and verify their existence. Several will be separated by pipes (the angles are referencials, do not put them). For Example: </AbsolutePath/Directory/file1>|</AbsolutePath/Directory/file2>|<...>|</path/Directory/fileN> Specifies an output file in which will be kept emails of verified domains. syntaxes: </AbsolutePath/OutputDirectory/targetFileName> File in which will be kept emails of no existent domains. syntaxes: </AbsolutePath/OutputDirectory/rejectedFileName> File in which will be kept emails of timedout domains. syntaxes: </AbsolutePath/OutputDirectory/failuresFileName> IMPORTANT NOTE: All parameters are obligated, leave blank to ignore.

Added you to git of custom list verifier / manager.

**Comment by sdwolfe32** [comment]
I'm not sure what you're saying anymore but since it has nothing to do with database I'll close the issue. Thanks
