### ISSUE TITLE
Join TDV

### ISSUE THREAD

**Issue by cindersec** [sdwolfe32/trumail#38]
ThunderDataVerify is truly a honest email verification company. 

I want to get you paid for work you do. I’m not greedy.

2 man project you and https://github.com/vodolaz095 

https://thunderdataverify.com

Got 100k usd in servers I think you can use and I know passion is everything that’s what I have aswell. I don’t do it for $ 

You need a few dns servers etc.

**Comment by sdwolfe32** [comment]
I'm really not interested in joining or working with anyone right now. I have a full time job and like I've told you this is a just a side project
