### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by davidusany** [sdwolfe32/trumail#40]
Hey @sdwolfe32 😊

Thanks for making such script. I have few questions:

1. If I install on my server am I dependent on your or any other service?
2. Do I have to pay or I can contribute some as per my reach?
3. Does this script can be installed on CentOS 6 server?

Thanks

**Comment by davidusany** [comment]
Thanks will contact you 😊

1. Does your script rotate IPs or how it can make lot of request?
2. What is needed such as VPS, IPs, etc.?

**Comment by sdwolfe32** [comment]
Trumail is a limited service that you can use up to 1000 req/day. The smtp verification portion is open source so you can attempt to run/host it yourself. If you run into problems you can either solve them yourself or consider supporting the developer by paying for the extended service. In other words, These are questions you'll need to answer for yourself.
