### ISSUE TITLE
Error Compling the new update version

### ISSUE THREAD

**Issue by branson12** [sdwolfe32/trumail#42]
# command-line-arguments
.\main.go:25:27: not enough arguments in call to verifier.NewVerifier
        have (string, string)
        want (int, string, string)
.\main.go:26:7: undefined: api.NewService
.\main.go:35:22: cannot convert ":" to type int
.\main.go:35:22: invalid operation: ":" + config.Port (mismatched types string and int)

**Comment by sdwolfe32** [comment]
Make sure to do a full `make glide` to pull in the latest of all the dependencies before you try to run the service
