### ISSUE TITLE
Result from api and library not sample

### ISSUE THREAD

**Issue by coderdaudat** [sdwolfe32/trumail#45]
I tried some email address on https://trumail.io/ and run example 
```
func main() {
  v := trumail.NewVerifier("YOUR_HOSTNAME.COM", "YOUR_EMAIL@DOMAIN.COM")
  
  // Validate a single address
  log.Println(v.Verify("test@gmail.com"))
}
```
Result I got doesn't sample.
Almost gmail it's OK but yahoo mail or hot mail or aol mail log null

**Comment by sdwolfe32** [comment]
This is likely an issue with your port 25 being blocked. This is a problem you'll need to solve on your end.
