### ISSUE TITLE
404 page not found on heroku.com

### ISSUE THREAD

**Issue by ilearnbydoing** [sdwolfe32/trumail#5]
Hi, 

Many congratulations for this work.

It can be an opensource alternative to neverbounce.com, datavalidation.com etc.

I am new to GO though I tried to run via heroku seems static site is not loading. it says 404 page not found is it normal?

thanks

**Comment by sdwolfe32** [comment]
Try setting the environment variable `SERVE_WEB` to `true` in Heroku.

**Comment by ilearnbydoing** [comment]
Thanks it worked.
