### ISSUE TITLE
Unable to send request to local machine

### ISSUE THREAD

**Issue by kumarkeviv** [sdwolfe32/trumail#50]
Hello

I am trying to use the docker image, the installation worked perfectly. The system says "http server started on [::]:8080".

But when I make a GET request to the system I get "{"message": "Not Found"}".

My request is in this format:
Type: GET 
URL: http://localhost:8080/json?email=abc@gmail.com

Is there anything wrong with my request? Any help will be great, thanks.

**Comment by s32x** [comment]
Please read the documentation. I don't write it for nothing.

**Comment by kumarkeviv** [comment]
Thanks

But I still can't understand the documentation, I was using the olderversion of trumail and in that there was no token parameter but it seems this new version requires one.

I understand I can the token when I use Trumail API but how to generate token when its running on my local machine as a docker deployment?

I am sorry if this sounds silly question but I really can't understand.
