### ISSUE TITLE
Not able to verify with updated build

### ISSUE THREAD

**Issue by kumarkeviv** [sdwolfe32/trumail#51]
Hi

Thanks for such a great product.

Recently I updated my module to latest docker image and it seems its not able to verify the emails anymore.

I am sending the request in this format "http://api.localhost:8080/v1/json/email=anyvalidmail@gmail.com". Every time I hit it responds back with deliverable as FALSE.

I also tested the same on my Heroku and still same issue (to make sure if my local IP was black listed).

Old version of same project is working fine in Heroku, could you please help me understand what I am doing wrong?

Thanks

**Comment by s32x** [comment]
What email "address" does the output say it's trying to verify?

**Comment by kumarkeviv** [comment]
I am sorry I understand my mistake now I was sending "email=" in the parameter.

Thanks :)
