### ISSUE TITLE
Different API (public/selfosted) answers

### ISSUE THREAD

**Issue by andycee** [sdwolfe32/trumail#52]
Hi! Thank you for your service. We used it on a paid terms and now want to use selfhosted docker version. Almost all work well but when I try to check email without MX entries or nonexistent host, latest version returns:
```json
{
  "message": "Mail server does not exist",
  "details": "lookup 4356.iy on 8.8.8.8:53: no such host"
}
```

but test API on https://trumail.io returns:
```json
{
    "address": "andrey@4356.iy",
    "username": "andrey",
    "domain": "4356.iy",
    "md5Hash": "c720cf8b88312322fa71c777979cc355",
    "validFormat": true,
    "deliverable": false,
    "fullInbox": false,
    "hostExists": false,
    "catchAll": false,
    "gravatar": false,
    "role": false,
    "disposable": false,
    "free": false
}
```

is there any way to get same message format from selfhosted version?

**Comment by s32x** [comment]
No, The paid version has more features and we do not provide support for self-hosting.
